const CSV_URL='https://docs.google.com/spreadsheets/d/e/2PACX-1vTF3wBIZH3SrknpKPNrTUpornzkLmFa7Pm0g40-V4gPZSv4ILdpGfnpZtsY2K0OZNxbljAvlaGoxZNr/pub?gid=953634781&single=true&output=csv';
const FIELDS={id:'ID',university:'Universidad',unit:'Vicerrectorado/Unidad Funcional Dependiente',technical:'Denominación Unidad Técnica, Gestora o Administrativa',email:'Correo electrónico de contacto',phone:'Teléfono de contacto',name:'Nombre de la Actividad / Acción / Iniciativa',description:'Descripción de la Actividad / Acción / Iniciativa (máx. 250 palabras)',url:'Dirección Web / URL Específica',scope:'Ámbito de Actuación',type:'Tipo de Actividad',timing:'Temporalidad',funding:'Financiación',cost:'Coste de la actuación',audience:'Población destinataria',space:'Espacio de realización'};
const FILTERS=[['university','Universidad'],['scope','Ámbito de actuación'],['type','Tipo de actividad'],['timing','Temporalidad'],['funding','Financiación'],['audience','Población destinataria'],['space','Espacio de realización']];
const state={headers:[],rows:[],filtered:[]};
const $=id=>document.getElementById(id); const clean=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim(); const display=s=>String(s??'').trim();
function parseCSV(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&quoted&&n==='"'){cell+='"';i++;continue}if(c==='"'){quoted=!quoted;continue}if(c===','&&!quoted){row.push(cell);cell='';continue}if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&n==='\n')i++;row.push(cell);cell='';if(row.some(v=>v.trim()!==''))rows.push(row);row=[];continue}cell+=c}if(cell||row.length){row.push(cell);if(row.some(v=>v.trim()!==''))rows.push(row)}return rows}
function column(row,name){const i=state.headers.indexOf(name);return i<0?'':row[i]??''} function values(row,key){return column(row,FIELDS[key]).split('|').map(display).filter(Boolean)}
function buildFilters(){const box=$('filters');box.innerHTML='';FILTERS.forEach(([key,label])=>{const options=[...new Set(state.rows.flatMap(r=>values(r,key)))].sort((a,b)=>clean(a).localeCompare(clean(b),'es'));const wrap=document.createElement('div');wrap.className='filter-field';const id='filter-'+key;wrap.innerHTML=`<label for="${id}">${label}</label><select id="${id}" data-filter="${key}"><option value="">Todos</option>${options.map(o=>`<option value="${escapeHTML(o)}">${escapeHTML(o)}</option>`).join('')}</select>`;box.append(wrap)});box.querySelectorAll('select').forEach(s=>s.addEventListener('change',applyFilters))}
function escapeHTML(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function applyFilters(){const query=clean($('search').value);const selected={};$('filters').querySelectorAll('select').forEach(s=>selected[s.dataset.filter]=clean(s.value));state.filtered=state.rows.filter(r=>{const hay=clean([column(r,'Universidad'),column(r,FIELDS.name),column(r,FIELDS.description),column(r,FIELDS.unit)].join(' '));return(!query||hay.includes(query))&&FILTERS.every(([key])=>!selected[key]||values(r,key).some(v=>clean(v)===selected[key]))});sortRows();render()}
function sortRows(){const [field,direction]=$('sort').value.split('-');const key=field==='name'?FIELDS.name:FIELDS.university;state.filtered.sort((a,b)=>clean(column(a,key)).localeCompare(clean(column(b,key)),'es')*(direction==='desc'?-1:1))}
function render(){const cards=$('cards');cards.innerHTML='';$('result-count').textContent=`${state.filtered.length} ${state.filtered.length===1?'resultado':'resultados'}`;$('download-csv').disabled=!state.filtered.length;if(!state.filtered.length){$('status').className='status';$('status').textContent='No hay iniciativas que coincidan con los criterios seleccionados.';return}$('status').textContent='';$('status').className='status';state.filtered.forEach((r,i)=>{const name=display(column(r,FIELDS.name))||'Iniciativa sin nombre';const desc=display(column(r,FIELDS.description));const card=document.createElement('article');card.className='card';card.innerHTML=`<div class="card-meta"><span>${escapeHTML(column(r,FIELDS.university))}</span><span>${escapeHTML(column(r,FIELDS.id))}</span></div><h3>${escapeHTML(name)}</h3><p>${escapeHTML(desc.length>190?desc.slice(0,187)+'…':desc)}</p><div class="card-footer"><span class="tag">${escapeHTML(column(r,FIELDS.type)||'Iniciativa')}</span><button class="details-link" type="button" data-index="${i}">Ver ficha →</button></div>`;cards.append(card)});cards.querySelectorAll('.details-link').forEach(b=>b.addEventListener('click',()=>openDialog(state.filtered[Number(b.dataset.index)])))}
function openDialog(row){const name=display(column(row,FIELDS.name))||'Iniciativa sin nombre';let html=`<h2 id="dialog-title" class="dialog-title">${escapeHTML(name)}</h2><dl class="detail-grid">`;Object.entries(FIELDS).filter(([key,label])=>key!=='id'&&display(column(row,label))).forEach(([key,label])=>{let value=display(column(row,label));if(key==='url'){const safe=/^https?:\/\//i.test(value)?value:'#';value=`<a class="external-link" href="${escapeHTML(safe)}" target="_blank" rel="noopener noreferrer">${escapeHTML(value)}</a>`}else if(key==='audience'){value=value.split('|').map(escapeHTML).join(' · ')}html+=`<div class="detail-item ${key==='description'?'full':''}"><dt>${escapeHTML(label)}</dt><dd>${key==='url'?value:escapeHTML(value)}</dd></div>`});$('dialog-content').innerHTML=html+'</dl>';$('initiative-dialog').showModal()}
function downloadCSV(){const separator=';';const lines=[state.headers,...state.filtered].map(row=>row.map(v=>{const s=String(v??'');return/[";\n\r]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}).join(separator));const blob=new Blob(['\uFEFF'+lines.join('\r\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='iniciativas-salud-mental-filtradas.csv';a.click();URL.revokeObjectURL(a.href)}
async function init(){try{const response=await fetch(CSV_URL,{cache:'no-store'});if(!response.ok)throw new Error(`HTTP ${response.status}`);const parsed=parseCSV(await response.text());state.headers=parsed.shift().map(display);state.rows=parsed.filter(r=>r.some(Boolean));const missing=Object.values(FIELDS).filter(f=>!state.headers.includes(f));if(missing.length)throw new Error('Faltan columnas esperadas: '+missing.join(', '));buildFilters();$('download-csv').addEventListener('click',downloadCSV);applyFilters()}catch(error){console.error('No se pudo cargar el CSV:',error);$('result-count').textContent='0 resultados';$('download-csv').disabled=true;$('status').className='status error';$('status').textContent='No se han podido cargar las iniciativas. Comprueba la conexión o la publicación del CSV e inténtalo de nuevo.'}}
['search','sort'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',applyFilters));$('clear-filters').addEventListener('click',()=>{$('search').value='';$('sort').value='name-asc';$('filters').querySelectorAll('select').forEach(s=>s.value='');applyFilters()});$('close-dialog').addEventListener('click',()=>$('initiative-dialog').close());init();
